import { notFound } from "next/navigation";
import { FileText } from "lucide-react";

import { BackLink } from "@/components/shell/back-link";
import { Card, CardContent } from "@/components/ui/card";
import { uuidSchema } from "@/lib/agents/validation";
import { requireUser } from "@/lib/auth/session";
import { outputFormatLabels } from "@/lib/missions/presentation";
import { getRepository } from "@/lib/repository";

/** Preview of a mission's document; stands in for Google Drive until Phase 3. */
export default async function MissionOutputPage({ params }: { params: Promise<{ missionId: string }> }) {
  const [{ missionId }, profile] = await Promise.all([params, requireUser()]);

  if (!uuidSchema.safeParse(missionId).success) {
    notFound();
  }

  const mission = await getRepository().getMission(profile.id, missionId);

  if (!mission || mission.status !== "completed" || !mission.outputText) {
    notFound();
  }

  const isSheet = mission.outputFormat === "google_sheet";
  const [heading, ...body] = mission.outputText.split("\n");
  const rows = isSheet ? body.filter((line) => line.includes(",")).map((line) => line.split(",")) : [];
  const notes = isSheet ? body.filter((line) => line.trim() && !line.includes(",")) : body;

  return (
    <>
      <BackLink href={`/missions/${mission.id}`}>Back to mission</BackLink>
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <FileText className="size-4" />
        {outputFormatLabels[mission.outputFormat]} preview · generated by {mission.agentName}
      </div>
      <Card className="mx-auto w-full max-w-4xl shadow-sm">
        <CardContent className="px-6 py-10 sm:px-14">
          <h1 className="text-2xl font-bold tracking-tight">{heading}</h1>
          {isSheet ? (
            <div className="mt-6 overflow-x-auto rounded-lg border">
              <table className="w-full text-sm">
                <tbody>
                  {rows.map((cells, index) => (
                    <tr className={index === 0 ? "bg-muted font-semibold" : "border-t"} key={index}>
                      {cells.map((cell, cellIndex) => (
                        <td className="px-3 py-2 whitespace-nowrap" key={cellIndex}>{cell}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : null}
          <div className="mt-6 space-y-3 text-[15px] leading-7">
            {notes.map((line, index) =>
              line.trim() === "" ? null : /^[A-Z][A-Za-z ]+$/.test(line) && line.length < 40 ? (
                <h2 className="pt-3 text-lg font-semibold" key={index}>{line}</h2>
              ) : (
                <p key={index}>{line}</p>
              ),
            )}
          </div>
        </CardContent>
      </Card>
    </>
  );
}
